### ISSUE TITLE
NameAndValue fields are mixed in different files.

### ISSUE THREAD

**Issue by burnout171** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#111]
For example in TapiNotification.swagger:
```
  NameAndValue:
    properties:
      valueName:
        type: string
        description: The name of the value. The value need not have a name.
      value:
        type: string
        description: The value
    description: A scoped name-value pair
```

In TapiTopology.swagger:
```
  NameAndValue:
    description: A scoped name-value pair
    properties:
      value:
        type: string
        description: The value
      valueName:
        type: string
        description: The name of the value. The value need not have a name.
```

During the check we observed that TapiTopology NameAndValue version is widely used. Could you please fix it in TapiNotification.swagger?
