### ISSUE TITLE
TapiNotification.swagger contain TimeRange with field in a different sequence than other swagger files.

### ISSUE THREAD

**Issue by NikolayKolyada** [OpenNetworkingFoundation/Snowmass-ONFOpenTransport#154]
TapiNotification.swagger contain TimeRange with field in a different sequence than other swagger files.

TapiNotification.swagger :
```
  TimeRange:
    properties:
      startTime:
        type: string
        description: none
      endTime:
        type: string
        description: none
    description: none
```

Other swagger files:
```
  TimeRange:
    description: none
    properties:
      endTime:
        type: string
        description: none
      startTime:
        type: string
        description: none
```

Different field sequence is bad for object compare after code generation.
Please resolve it.
Thanks!
